name: Deploy MkDocs (gh-deploy)
on:
  workflow_dispatch: {}   # 手动触发一次即可；后面也可保留 push 触发
  push:
    branches: [ main ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.jpg'

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs build --strict
      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
